apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: petclinic-build-and-rollout
spec:
  workspaces:
    - name: shared-workspace
    - name: gitops-source
    - name: maven-settings-cm
  params:
    - name: app-name
      type: string
      description: name of the deployment to be patched
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: "master"
    - name: "gitops-url"
      value: "https://github.com/pittar-sandbox/openshift-gitops.git"
    - name: "gitops-revision"
      value: "main"
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
    - name: generate-id
      taskRef:
        name: generate-id
      runAfter:
        - clone-repository
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: mvn-gav
      taskRef:
        name: mvn-export-gav
        kind: Task
      runAfter:
        - clone-repository 
      params:
        - name: MAVEN_REPO_CONFIG_SECRET
          value: nexus-secret
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings-cm
    - name: mvn-build
      taskRef:
        name: maven
        kind: Task
      runAfter:
        - generate-id
        - mvn-gav
      params:
        - name: GOALS
          value: ["clean", "deploy", "sonar:sonar"]
        - name: MAVEN_REPO_CONFIG_SECRET
          value: nexus-secret
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings-cm
    - name: s2i-build
      taskRef:
        name: s2i-binary-build
        kind: Task
      runAfter:
        - mvn-build 
      params:
        - name: BUILD_NAME
          value: "$(params.app-name)-binary-build"
        - name: BINARY_PATH
          value: "/target/app.jar"
      workspaces:
        - name: build-workspace
          workspace: shared-workspace
    - name: tag-dev
      taskRef:
        name: tag-and-push-image
        kind: Task
      runAfter:
        - s2i-build
      params:
        - name: src-image
          value: "quay.io/pittar/petclinic:gitops-tekton"
        - name: dest-image
          value: "quay.io/pittar/petclinic"
        - name: dest-tags
          value: "$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid),gitops-tekton-dev"
    - name: rollout-dev
      taskRef:
        name: rollout-restart
        kind: Task
      runAfter:
        - tag-dev
      params:
        - name: APP_NAME
          value: "$(params.app-name)"
        - name: NAMESPACE
          value: "petclinic-dev"
    - name: tag-test
      taskRef:
        name: tag-and-push-image
        kind: Task
      runAfter:
        - rollout-dev
      params:
        - name: src-image
          value: "quay.io/pittar/petclinic:gitops-tekton-dev"
        - name: dest-image
          value: "quay.io/pittar/petclinic"
        - name: dest-tags
          value: "gitops-tekton-test"
    - name: rollout-test
      taskRef:
        name: rollout-restart
        kind: Task
      runAfter:
        - tag-test
      params:
        - name: APP_NAME
          value: "$(params.app-name)"
        - name: NAMESPACE
          value: "petclinic-test"
    - name: clone-gitops-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - rollout-test
      workspaces:
        - name: output
          workspace: gitops-source
      params:
        - name: url
          value: "$(params.gitops_url)"
        - name: revision
          value: "$(params.gitops_revision)"
        - name: deleteExisting
          value: "true"
    - name: branch
      taskRef:
        name: git
      runAfter:
        - clone-gitops-repo
      workspaces:
        - name: source
          workspace: gitops-source
      params:
        - name: commands
          value: |
            git checkout -b push-$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
    - name: patch-prod
      taskRef:
        name: kustomize
      params:
        - name: old-image
          value: petclinic
        - name: new-image
          value: quay.io/pittar/spring-petcinic
        - name: new-tag
          value: $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
        - name: overlaypath
          value: gitops/02-developers/overlays/prod/01-namespaces/petclinic-prod
      runAfter:
        - clone-gitops-repo
      workspaces:
        - name: source
          workspace: gitops-source
    - name: commit
      taskRef:
        name: git
      runAfter:
        - patch-prod
      workspaces:
        - name: source
          workspace: gitops-source
      params:
        - name: commands
          value: |
            tag="$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)"
            git status
            cat ~/.gitconfig
            git config --global user.email "pipeline@redhat.com"
            git add -u
            git commit -m 'Pushing image $(params.image_dest_url):$tag to production'
            git push origin push-$tag
    - name: prod-pr-deploy
      taskRef:
        name: task-create-pr
        kind: Task
      runAfter:
        - commit
      workspaces:
        - name: source
          workspace: gitops-source
      params:
        - name: title
          value: Update image to $(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
        - name: body
          value: |-
            Please review the following links before accepting the PR:
            Image Vulnerabilities: https://$(params.image_dest_url):$(tasks.generate-id.results.short-commit)-$(tasks.generate-id.results.build-uid)
