apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-canada-gitops/catalog/openshift-pipelines-tasks/rollout-restart/base?ref=master
  - github.com/redhat-canada-gitops/catalog/openshift-pipelines-tasks/maven/base?ref=master
  - github.com/redhat-canada-gitops/catalog/openshift-pipelines-tasks/s2i-binary-build/base?ref=master

resources:
  - 01-workspace-pvc.yaml
  - 01-gitops-repo-pvc.yaml
  - 02-build-and-rollout-pipeline.yaml
