kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: cicd-tools
spec:
  destination:
    namespace: cicd-tools
    server: https://kubernetes.default.svc
  project: cicd-tools
  source:
    path: gitops/overlays/03-cicd-tools
    repoURL: https://github.com/pittar-sandbox/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true