kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd-developers
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: environments
  source:
    path: gitops/overlays/01-environments/02-argocd-developers
    repoURL: https://github.com/pittar-sandbox/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true