kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: petclinic-environments
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: environments
  source:
    path: gitops/overlays/01-environments/04-petclinic
    repoURL: https://github.com/pittar-demos/gitops-and-tekton-with-openshift.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true