apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-test

bases:
  - ../../../../base/01-apps/petclinic

images:
  - name: petclinic
    newName: quay.io/pittar/petclinic
    newTag: gitops-tekton-test