kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  app: cicd-tools
  name: cicd-tools
spec:
  destination:
    namespace: cicd-tools
    server: https://kubernetes.default.svc
  project: cicd-tools
  source:
    path: gitops/02-developers/overlays/non-prod/01-cicd-tools
    repoURL: https://github.com/pittar-sandbox/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy