apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-cicd

bases:
  - ../../../../base/03-rbac/openshift-gitops

resources:
  - namespace.yaml
  - quay-sealedsecret.json
