apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-prod

bases:
  - ../../../../base/02-quotas-and-limits/02-medium
  - ../../../../base/03-rbac/openshift-gitops

resources:
  - namespace.yaml
  - petclinic-serviceaccount.yaml
