apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-prod

bases:
  - ../../../../base/01-apps/petclinic

images:
  - name: petclinic
    newName: image-registry.openshift-image-registry.svc:5000/petclinic-cicd/petclinic
    newTag: prod