apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-prod


images:
  - name: petclinic
    newName: quay.io/pittar/petclinic
    newTag: gitops-tekton-dev
resources:
- ../../../../base/01-apps/petclinic
