apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-prod


images:
- name: petclinic
  newName: quay.io/pittar/spring-petcinic
  newTag: 383da5b-705579173
resources:
- ../../../../base/01-apps/petclinic
