kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  generateName: petclinic-build-and-rollout-run-
spec:
  pipelineRef:
    name: petclinic-build-and-rollout
  params:
    - name: "git-url"
      value: "https://github.com/pittar/spring-petclinic.git"
    - name: "git-revision"
      value: "gitops-tekton"
    - name: "app-name"
      value: "petclinic"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace
    - name: maven-settings-cm
      configMap:
        name: maven-settings-cm