kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: petclinic-cicd
spec:
  destination:
    namespace: petclinic-cicd
    server: https://kubernetes.default.svc
  project: petclinic
  source:
    path: gitops/overlays/04-petclinic/01-cicd
    repoURL: https://github.com/pittar-sandbox/openshift-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true