apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-test

bases:
  - ../../../../base/02-quotas-and-limits/02-medium
  - ../../../../base/03-rbac/openshift-gitops
  - ../../../../base/03-rbac/petclinic-cicd-pipelines

resources:
  - namespace.yaml
  - quay-creds-secret-sealedsecret.json
