apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  # Main namespaces project.
  - namespaces-project.yaml
  # Argo CD Namespaces
  - openshift-gitops-app.yaml
  - argocd-app.yaml
  # Tooling Namespaces
  - cicd-tools-app.yaml
  - sealed-secrtes-app.yaml
  # Pet Clinic Namespaces
  - petclinic-cicd-app.yaml
  - petclinic-dev-app.yaml
  - petclinic-test-app.yaml