apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-cicd

# Nexus secret (username and password).
resources:
  - 01-nexus-secret.yaml

# Generator options.
generatorOptions:
  labels:
    app: maven-settings
  disableNameSuffixHash: true

# Create a ConfigMap from custom settings.xml file.
configMapGenerator:
  - name: maven-settings-cm
    files:
      - settings.xml
